name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with LFS
        uses: actions/checkout@v3
        with:
          lfs: true  # ✅ This ensures LFS pointer files are fetched

      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs pull  #downloads the ONNX file

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest onnxruntime

      - name: Run tests
        run: |
          pytest

      - name: Deploy to SageMaker
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: |
          python sagemaker_deploy_and_test.py
