name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with LFS
        uses: actions/checkout@v3
        with:
          lfs: true  # ✅ This ensures LFS pointer files are fetched

      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs pull  #downloads the ONNX file

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest onnxruntime

      - name: Run tests
        run: |
          pytest
